version: '3'
services:
  web:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: gunicorn priceFinder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static_volume:/pricefinder/staticfiles
    expose:
    - 8000
    container_name: pricefinder_container
    env_file:
      - variable.env

  nginx:
    build: ./nginx
    ports:
      - 8001:80
    depends_on:
      - web
    volumes:
      - ./static_volume:/pricefinder/staticfiles


  celery_worker:
    build: .
    command: celery -A priceFinder worker -l info
    container_name: celery_Worker_container
    depends_on:
      - web
    env_file:
      - variable.env

  celery_beat:
    build: .
    command: celery -A priceFinder beat -l info
    container_name: celery_beat_container
    depends_on:
      - web
    env_file:
      - variable.env


volumes:
  static_volume:
