version: '3'
services:
  web:
    build: .
    command: gunicorn priceFinder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static_volume:/pricefinder/staticfiles
    ports:
      - 8000:8000
    container_name: pricefinder_container
    env_file:
      - variable.env

  nginx:
      build: ./nginx
      ports:
        - 8001:80
      depends_on:
        - web
      volumes:
        - ./static_volume:/pricefinder/staticfiles

volumes:
  static_volume:
