version: '3'
services:
  pricefinder:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data/:/pricefinder/data/
    ports:
      - 8000:8000
    container_name: pricefinder_container

  
  celery_worker:
    build: .
    command: celery -A priceFinder worker -l info
    container_name: celery_Worker_container

  celery_beat:
    build: .
    command: celery -A priceFinder beat -l info
    container_name: celery_beat_container

  
volumes:
  data: