version: "3"
services:
  web:
    build: .
    command: sh -c "gunicorn priceFinder.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static_volume:/djangoapp/staticfiles/
    expose:
      - 8000
    container_name: pricefinder_container1
    env_file:
      - variable.env
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./static_volume:/djangoapp/staticfiles/
    restart: always

volumes:
  static_volume:

