version: "3"
services:
  web:
    build: .
    command: sh -c "gunicorn priceFinder.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static_volume:/djangoapp/staticfiles/
    expose:
      - 8000
    container_name: pricefinder_container1
    env_file:
      - variable.env

  nginx:
    build: ./nginx
    ports:
      - 8001:80
    depends_on:
      - web
    volumes:
      - ./static_volume:/djangoapp/staticfiles/
      - ./scrapy_volume:/djangoapp/scrapy_data

  celery_worker:
    build: .
    command: celery -A priceFinder worker -l info  --pool=gevent -Ofair
    container_name: celery_Worker_container
    volumes:
      - .scrapy_volume:/djangoapp/scrapy_data
    depends_on:
      - web
    env_file:
      - variable.env
    restart: always

  celery_beat:
    build: .
    command: celery -A priceFinder beat -l info
    container_name: celery_beat_container
    depends_on:
      - web
    env_file:
      - variable.env

  flower:
    image: mher/flower
    container_name: flower_container
    command: celery flower
    restart: always
    depends_on:
      - celery_worker
    environment:
     - CELERY_BROKER_URL="amqp://admin@3.145.24.76:5672/"
     - FLOWER_PORT=8888
    ports:
      - 8888:8888 
    volumes:
      - ./flower_data:/data

volumes:
  static_volume:
  scrapy_volume:
  flower_data:
