version: "3"
services:
  web:
    build: .
    command: sh -c "gunicorn priceFinder.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - /static_volume:/djangoapp/staticfiles/
    expose:
      - 8000
    container_name: pricefinder_container1
    env_file:
      - variable.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - /static_volume:/djangoapp/staticfiles/
      - /scrapy_volume:/djangoapp/scrapy_data

  celery_worker:
    build: .
    command: celery -A priceFinder worker -l info  --pool=gevent -Ofair
    container_name: celery_Worker_container
    volumes:
      - /scrapy_volume:/djangoapp/scrapy_data
    depends_on:
      - web
    env_file:
      - variable.env
    restart: always

  celery_beat:
    build: .
    command: celery -A priceFinder beat -l info
    container_name: celery_beat_container
    depends_on:
      - web
    env_file:
      - variable.env


volumes:
  static_volume:
  scrapy_volume:
  flower_data:
