version: '3'
services:
  web:
    build: .
    command: gunicorn priceFinder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static_volume:/pricefinder/staticfiles
    expose:
    - 8000
    container_name: pricefinder_container
    env_file:
      - variable.env

volumes:
  static_volume:
