# Generated by Django 4.2 on 2023-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('discount_price', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('product_url', models.URLField()),
                ('discount_percent', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-discount_percent'],
            },
        ),
    ]
