# Generated by Django 4.2 on 2023-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
