# Generated by Django 4.2 on 2023-05-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(),
        ),
    ]
